# Configuration for Slack conversation fetcher with B2 storage
storage:
  type: "b2"  # Options: "local", "b2"
  b2:
    bucket_name: "${B2_SLACK_BUCKET_NAME}"
    application_key_id: "${B2_SLACK_KEY_ID}"
    application_key: "${B2_SLACK_APP_KEY}"
    # Optional: specify a subdirectory in the bucket
    path_prefix: "slack-conversations/"
    # B2 S3-compatible endpoint - usually s3.us-west-<region>.backblazeb2.com
    # Check your B2 bucket details for the correct endpoint
    endpoint: "${B2_ENDPOINT:-https://s3.us-west-004.backblazeb2.com}"

slack:
  # Slack tokens - these will be read from environment variables
  xoxc_token: "${SLACK_MCP_XOXC_TOKEN}"
  xoxd_token: "${SLACK_MCP_XOXD_TOKEN}"
  xoxp_token: "${SLACK_MCP_XOXP_TOKEN}"

# Default fetch settings (can be overridden by command line flags)
defaults:
  limit_per_channel: 0
  output_format: "json"  # console, json, csv
  channels_filter: "all"  # all, public, private
  
# File naming configuration
file_naming:
  # Include timestamp in filename
  include_timestamp: true
  # Include date range in filename
  include_date_range: true
  # Include channels filter in filename
  include_channels: true
  # Custom prefix for filenames
  prefix: "conversations"