name: Daily Composer CSV to B2

on:
  schedule:
    # Runs daily at 14:05 UTC (7:05am PDT / 6:05am PST).
    - cron: '5 14 * * *'
  workflow_dispatch: {}

jobs:
  fetch-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Install rclone
        run: |
          curl -fsSL https://rclone.org/install.sh | sudo bash

      - name: Configure rclone for B2
        env:
          B2_KEY_ID: ${{ secrets.B2_KEY_ID }}
          B2_APP_KEY: ${{ secrets.B2_APP_KEY }}
        run: |
          mkdir -p ~/.config/rclone
          cat > ~/.config/rclone/rclone.conf <<EOF
          [b2]
          type = b2
          account = ${B2_KEY_ID}
          key = ${B2_APP_KEY}
          hard_delete = true
          EOF

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Download and Fix CSV
        env:
          URL: ${{ secrets.CSV_URL }}
        run: |
          set -euo pipefail
          mkdir -p data
          TS=$(date -u +"%Y-%m-%d_%H-%M-%S")
          RAW_OUT="data/raw_${{ secrets.CSV_OUTPUT_PREFIX }}_${TS}.csv"
          OUT="data/${{ secrets.CSV_OUTPUT_PREFIX }}_${TS}.csv"
          
          # Download raw CSV
          curl -fSL "$URL" -o "$RAW_OUT"
          
          # Optional sanity checks (fail if empty or suspiciously small)
          test -s "$RAW_OUT"
          [ $(wc -c < "$RAW_OUT") -gt 100 ] || (echo "File too small" && exit 1)
          
          # Fix CSV newlines and validate
          python3 fix_csv.py "$RAW_OUT" -o "$OUT" --validate
          
          # Clean up raw file
          rm "$RAW_OUT"
          
          echo "Fixed CSV ready: $OUT"

      - name: Upload to B2 via rclone
        env:
          B2_BUCKET: ${{ secrets.B2_BUCKET }}
        run: |
          set -euo pipefail
          # Put files under /composer/YYYY/MM/ for tidy partitioning
          YEAR=$(date -u +"%Y")
          MONTH=$(date -u +"%m")
          rclone copy ./data "b2:${B2_BUCKET}/${{ secrets.CSV_OUTPUT_PREFIX }}/${YEAR}/${MONTH}/" \
            --fast-list --ignore-existing --checksum --transfers=4 --checkers=8
